/* 
**  mod_research_request.c -- Apache sample research_request module
**  [Autogenerated via ``apxs -n research_request -g'']
**
**  To play with this sample module first compile it into a
**  DSO file and install it into Apache's modules directory 
**  by running:
**
**    $ apxs -c -i mod_research_request.c
**
**  Then activate it in Apache's httpd.conf file for instance
**  for the URL /research_request in as follows:
**
**    #   httpd.conf
**    LoadModule research_request_module modules/mod_research_request.so
**    <Location /research_request>
**    SetHandler research_request
**    </Location>
**
**  Then after restarting Apache via
**
**    $ apachectl restart
**
**  you immediately can request the URL /research_request and watch for the
**  output of this module. This can be achieved for instance via:
**
**    $ lynx -mime_header http://localhost/research_request 
**
**  The output should be similar to the following one:
**
**    HTTP/1.1 200 OK
**    Date: Tue, 31 Mar 1998 14:42:22 GMT
**    Server: Apache/1.3.4 (Unix)
**    Connection: close
**    Content-Type: text/html
**  
**    The sample page from mod_research_request.c
*/ 

#include "httpd.h"
#include "http_config.h"
#include "http_protocol.h"
#include "ap_config.h"
/*
#include "http_connection.h"
#include "http_core.h"
#include "http_log.h"
#include "http_protocol.h"
#include "http_request.h"
#include "ap_listen.h"
#include "apr_strings.h"
#include "apr_portable.h"
#include "apr_optional.h"
*/


/* The sample content handler */
static int research_request_handler(request_rec *r)
{
    r->content_type = "text/plain";      

    ap_rputs("************************\n",r);
    ap_rputs("* Mod Research Reqeust *\n",r);
    ap_rputs("************************\n",r);

    ap_rprintf(r, "protocol: %s\n", r->protocol);
    ap_rprintf(r, "method: %s\n", r->method);
    ap_rprintf(r, "method_number: %d\n", r->method_number);
    ap_rprintf(r, "uri: %s\n", r->uri);
    ap_rprintf(r, "args: %s\n", r->args ? r->args : "");
    ap_rprintf(r, "client ip: %s\n", r->connection->client_ip);
    ap_rprintf(r, "local ip: %s\n", r->connection->local_ip);
    ap_rprintf(r, "useragent: %s\n", apr_table_get(r->headers_in, "User-Agent") ? 
                                     apr_table_get(r->headers_in, "User-Agent") : "");
    ap_rprintf(r, "referer: %s\n",   apr_table_get(r->headers_in, "Referer") ? 
                                     apr_table_get(r->headers_in, "Referer") : "");
    ap_rprintf(r, "server_admin: %s\n", r->server->server_admin);

    return OK;
}

static void research_request_register_hooks(apr_pool_t *p)
{
    ap_hook_handler(research_request_handler, NULL, NULL, APR_HOOK_MIDDLE);
}

/* Dispatch list for API hooks */
module AP_MODULE_DECLARE_DATA research_request_module = {
    STANDARD20_MODULE_STUFF, 
    NULL,                  /* create per-dir    config structures */
    NULL,                  /* merge  per-dir    config structures */
    NULL,                  /* create per-server config structures */
    NULL,                  /* merge  per-server config structures */
    NULL,                  /* table of config file commands       */
    research_request_register_hooks  /* register hooks                      */
};

